### ISSUE TITLE
False configuration values don't work

### ISSUE THREAD

**Issue by kennu** [morenofa/react-global-configuration#1]
I'm unable to use configuration setting that are set to `false` or `null`, which seems to be caused by this line:

https://github.com/morenofa/react-global-configuration/blob/master/lib/configuration.js#L54

**Comment by singhalsurbhi07** [comment]
any progress on this issue. I am using this library and facing this issue

**Comment by morenofa** [comment]
True, you can't use null or false values. I will solve that as soon as possible. 

Thx!

**Comment by morenofa** [comment]
I have released a new version fixing this bug. Thanks for the report.

**Comment by morenofa** [comment]
I have released a new version fixing this bug. Thanks for the report.
