### ISSUE TITLE
When setting more than one configuration value the second one gets an object

### ISSUE THREAD

**Issue by ghost** [morenofa/react-global-configuration#2]
I set two configuration values:

config.set(
	{
		apiBasePath: 'http://localhost:8088/api',
		saveEditsInstantly: false
	});

When reading the first one (config.get('apiBasePath')) I correctly get the assigned value. When reading the second one (config.get('saveEditsInstantly')) I get an object with all configuration settings:

{apiBasePath: "http://localhost:8088/api", saveEditsInstantly: false}

**Comment by morenofa** [comment]
I have released a new version solving this problem. Thx for the report!!
