### ISSUE TITLE
Get config value for nested objects

### ISSUE THREAD

**Issue by vireshshah** [morenofa/react-global-configuration#3]
I'm having my JSON like below which I'm setting using config.set method. I'm not able to get value for nested object. I'm trying like `config.get('cart.total')`. It's returning null. Any help would be appreciated.

```
{
    "firstName":  "ABC",
    "cart": {
        "total": 1234
    }
}
```

**Comment by morenofa** [comment]
Nowadays you can't get the value of a nested object, but I think it is a very good idea and and will be implemented it in future versions. I'll let you know when this new feature is available. 

Thank you very much!

**Comment by vireshshah** [comment]
Thanks @morenofa. It would be super helpful. However I fixed it by flattening json before using `config.set`. I used below function to flatten json (https://stackoverflow.com/a/19101235). I think you can utilize same in your code and you're good to go. Thanks again for prompt reply.

```
let flattenJSON = (data) => {
    var result = {};
    function recurse (cur, prop) {
        if (Object(cur) !== cur) {
            result[prop] = cur;
        } else if (Array.isArray(cur)) {
             for(var i=0, l=cur.length; i<l; i++)
                 recurse(cur[i], prop + "[" + i + "]");
            if (l == 0)
                result[prop] = [];
        } else {
            var isEmpty = true;
            for (var p in cur) {
                isEmpty = false;
                recurse(cur[p], prop ? prop+"."+p : p);
            }
            if (isEmpty && prop)
                result[prop] = {};
        }
    }
    recurse(data, "");
    return result;
}
```

**Comment by morenofa** [comment]
I just released a new version with these improvements. 

Thank you very much!

**Comment by vireshshah** [comment]
Thanks a lot.
